### ISSUE TITLE
Integrate with `Meteor JS + Element UI`

### ISSUE THREAD

**Issue by thearabbit** [ratiw/vuetable-2-tutorial#46]
I base on Meteor + Element UI.
but I don't understand to integrate (server usage -> Meteor Methods).
Have anyone help me.

**Comment by ratiw** [comment]
@thearabbit Sorry, I just don't have any idea on bot Meteor JS or Element UI. But Vuetable just need an API endpoint that it can work with. If you can explain the problem in more detail, maybe we can work something out.

**Comment by thearabbit** [comment]
Thanks for your reply.
I will try

**Comment by thearabbit** [comment]
Excuse me, It have problem or not if I have big data (1,000,000+)?

**Comment by ratiw** [comment]
@thearabbit If you plan to load all of those data at once to be rendered on the client side for display only a subset of it, "anything" will have a problem. Vuetable is not a data store or temporary storage, it is just a component that will rendered HTML table from your portion of data. 

The idea is to display paginated data! 

Think like this, you will always be able to display table data for a certain number of rows, e.g. 15 rows per page. Displaying more than that is not practical because the page will get to tall to fit into the screen. So, even though you have 1,000,000+ records of data, but you only fetch it 15 at a time to be displayed and when the user what to see the next page, you fetch the next 15 more, on and on. By dividing the data into pages, you can allow the user to fetch any page at anytime by calculating the beginning and ending records from the page number and the page size.

Vuetable is designed for this and can work with 1,000,000+ easily because it only deal with a small portion of data at a time. If you expect to fetch 1,000,000+ data at once, your browser might lockup first because it ran out of RAM even before throwing them into Vuetable. You need to understand about paginated data first before start doing anything.
