### ISSUE TITLE
pagination error : this._init is not a function

### ISSUE THREAD

**Issue by figoxu** [ratiw/vuetable-2-tutorial#7]
.1.2.0@vuetable-2/src/components/VuetablePaginationMixin.vue
Module build failed: TypeError: this._init is not a function
![default](https://cloud.githubusercontent.com/assets/10055828/22450715/82604cd0-e7a3-11e6-80c6-cc28bce360e2.png)

What's wrong ? How can i solve that problem ?

**Comment by ratiw** [comment]
@figoxu I'm not sure, but I've noticed a warning message in the above screenshot.
```
[Vue warn]: Vue is a constructor and should be called with the `new` keywork
```

It seems like you initiates Vue without `new` keyword. Try checking your code again.

**Comment by figoxu** [comment]
I just using  81a5bb4d86be3a3b4588854c4a260274d429e82a  
![default](https://cloud.githubusercontent.com/assets/10055828/22460508/15ced70c-e7e0-11e6-9477-03375253a78a.png)

![default](https://cloud.githubusercontent.com/assets/10055828/22460629/b647d5e4-e7e0-11e6-9268-c30a2c5ecd30.png)

**Comment by ratiw** [comment]
@figoxu It is still working as expected on my side. I checkout `81a5bb4`, verify that it is exactly as your screenshot, and run using `npm`, but I never see that warning message and everything runs fine. But my NPM version is 3.10.10.

Do you have problem with all other lessons or just lesson-7?  Are you using Vue 2.x or Vue 1.x because Vuetable-2 is for Vue 2.x. 

Maybe try updating NPM version, remove everything in `node_modules` and try `npm install` again.

**Comment by figoxu** [comment]
What a pity of npm install .  < __<   
I am using yarn install instead of npm install , It should be ok .  tks  : )  .
